config/routes.rb
Apipage::Application.routes.draw do
  
  get "users/new"

  root :to => 'Pages#home'
  
  match '/blog',    to: 'pages#blog'
  match '/home',    to: 'pages#home'
  
  match '/getstarted', to: 'pages#getstarted'
  match '/getstarted/ios', to: 'pages#ios'
  match '/getstarted/android', to: 'pages#android'
  match '/getstarted/wp', to: 'pages#wp'
  match '/getstarted/as', to: 'pages#as'
  match '/getstarted/html5', to: 'pages#html5'
  match '/getstarted/unity', to: 'pages#unity'
  match '/getstarted/pg', to: 'pages#pg'
  match '/getstarted/corona', to: 'pages#corona'
  match '/getstarted/marmalade', to: 'pages#marmalade'
  
  
  match '/pricing', to: 'pages#pricing'
  
  match '/docs', to: 'pages#docs'
  
  match '/support', to: 'pages#support'
  match '/support/contact', to: 'pages#contact'
  match '/support/forum', to: 'pages#forum'
  
  match '/signup', to: 'users#new'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def getstarted
  end
  
  def pricing
  end

  def blog
  end

  def docs
  end

  def support
  end
  
  def ios
  end
  
  def android
  end
  
  def wp
  end
  
  def as
  end
  
  def html5
  end
  
  def contact
  end
  
  def forum
  end
  
  def unity
  end
  
  def pg
  end
  
  def corona
  end
  
  def marmalade
  end
  
  def signup
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
      base_title = "Klick Push Developer Center"
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
      end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer">
  <small>
    <p>&copy; Klick Push 2012</p>
  </small>
  <nav class="bottom">
    <ul>
		<li><%= link_to "Home", home_path %>
      	<li><%= link_to "Get Started",    getstarted_path %></li>
		<li><%= link_to "Documentation",    docs_path %></li>
		<li><%= link_to "Blog", blog_path %></li>
		<li><%= link_to "Support", support_path %></li>
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
    		<%= link_to image_tag("klickpush-logo-small.png", id: "logo", alt: "Klick Push Developer Center"), home_path %>
      		<nav>
        		<ul class="nav pull-right">
          			<li><%= link_to "Get Started",    getstarted_path %></li>
					<li><%= link_to "Pricing", pricing_path %>
          			<li><%= link_to "Documentation",    docs_path %></li>
          			<li><%= link_to "Blog", blog_path %></li>
		  			<li class="dropdown" id="menu1">
					    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
					      Support
					      	<b class="caret"></b>
					    </a>
					    <ul class="dropdown-menu">
					    	<li><a href="<%= support_contact_path %>">Contact Us</a></li>
					      	<li><a href="<%= support_forum_path %>">Developer Forum</a></li>
						</ul>
					</li>
					<li><%= link_to "Sign Up", signup_path %></li>
        		</ul>
      		</nav>
		</div>
  	</div>
</header>

app/views/layouts/_platforms.html.erb
<div class="well sidebar-nav">
	<ul class="nav nav-list">
    	<li class="nav-header">Platforms</li>
       	<li><%= link_to "iOS",    getstarted_ios_path %></li>
        <li><%= link_to "Android",    getstarted_android_path %></li>
		<li><%= link_to "Windows Phone", getstarted_wp_path %></li>
        <li><%= link_to "Actionscript", getstarted_as_path %></li>
		<li><%= link_to "HTML5", getstarted_html5_path %></li>
        <li class="nav-header">Integrations</li>
        <li><%= link_to "Unity", getstarted_unity_path %></li>
		<li><%= link_to "Phone Gap", getstarted_pg_path %></li>
		<li><%= link_to "Corona", getstarted_corona_path %></li>
        <li><%= link_to "Marmalade", getstarted_marmalade_path %></li>
	</ul>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_usps.html.erb
<div class="container-fluid">
	<div class="row-fluid">
        <div class="span4">
          <h2>Manage Your Own Goods</h2>
           <p>If you manage your own virtual goods, you can integrate Klick Push to help incentivize users to purchase. If you can parse a JSON file, we can show you how to achieve conversions between 12-18%.</p>
          <p><%= link_to "Learn More", getstarted_path, class: "btn btn-large" %></p>
        </div>
        <div class="span4">
          <h2>Drag and Drop UI</h2>
           <p>We've integrated with Roar Engine to provide you with a drag and drop solution. Bring your goods in, set the events, choose your genres, and include the Roar file in your project. It's that easy! </p>
          <p><%= link_to "Visit Roar.io", "http://roarengine.com", target: "_blank", class: "btn btn-large" %></p>
       </div>
        <div class="span4">
          <h2>Retarget Users</h2>
          <p>Once we've acquired the user, we work on your behalf to make you money through our targeted email marketing engine. Don't worry we won't sell their information to third parties or spam them with BS offers.</p>
          <p><%= link_to "Learn More", getstarted_path, class: "btn btn-large" %></p>
        </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title><%= full_title(yield(:title)) %></title>
  		<%= stylesheet_link_tag    "application", media: "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
	    <div class="container">
			<%= yield %>
		</div>
		
		<%= render 'layouts/footer'%>
	  </body>
</html>

app/views/pages/android.html.erb
<% provide(:title, 'Get Started | Android') %>
<div class="container">
  <div class="row-fluid">
    <div class="span3">
    	<%= render 'layouts/platforms'%>
    </div>
	<div class="span9">
    	<h1>Get started with Android</h1>
		<p>Coming soon.</p>
	</div>
</div>

app/views/pages/as.html.erb
<% provide(:title, 'Get Started | Actionscript') %>
<div class="container">
  <div class="row-fluid">
    <div class="span3">
    	<%= render 'layouts/platforms'%>
    </div>
	<div class="span9">
    	<h1>Get started with Actionscript</h1>
		<p>Coming soon.</p>
	</div>
</div>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Klick Push</h1>
<p>Contact info will go here</p>

app/views/pages/corona.html.erb
<% provide(:title, 'Get Started | Corona') %>
<div class="container">
  <div class="row-fluid">
    <div class="span3">
    	<%= render 'layouts/platforms'%>
    </div>
	<div class="span9">
    	<h1>Get started with Corona</h1>
		<p>Coming soon.</p>
	</div>
</div>

app/views/pages/docs.html.erb
<% provide(:title, 'Documentation') %>
<div class="container">
	<div class="row">
		<div class="span12">
			<h1>Klick Push REST API Reference</h1>
			<p>The Klickpush API gives partners and independent developers access to the full range of Klickpush functionality. The API employs a set of OAuth-protected JSON/REST HTTP endpoints accessible at api.klickpush.com. To get started, contact <a href="mailto:devaris@klickpush.com">devaris@klickpush.com</a> to receive credentials</p>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<p><h2>Users</h2></p>
			<h3>To create a new user on the Klickpush platform, issue an HTTP POST to /users (OAuth required); the acting principal must have user creation authorization. On success, the API returns an HTTP 201 response (Created) with data about the new user.</h3>
			<div class="row-fluid">
				<div class="span3"><br /><p>POST /users</p></div>
			    <div class="span6"><br /><p>Returns info about user that's authorized to make calls to platform</p></div>
			</div>
			<div class="row-fluid">
				<div class="span3"><p>Example Request</p></div>
			    <div class="span6"><p>URL: http://api.klickpush.com/users</p></div>
			</div>
			<div class="row-fluid">
				<div class="span3"><p>Sample Response</p></div>
			    <div class="span6"><p><code>=> {"id"=>257, "access_token"=> {"key"=>"EGSCKISLDH", "secret"=>"ETSMEGRLRH"}}
				# Note: new access token's consumer credentials are those used to create the user.</code></p></div>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="span12">
			<p><h2>Genres</h2></p>
			<h3>To list all the musical genres Klickpush supports, issue an HTTP GET to /genres (OAuth required).</h3>
			<div class="row-fluid">
				<div class="span3"><br /><p>GET /genres</p></div>
			    <div class="span6"><br /><p>Returns list of all available genres</p></div>
			</div>
			<div class="row-fluid">
				<div class="span3"><p>Example Request</p></div>
			    <div class="span6"><p>URL: http://api.klickpush.com/genres</p></div>
			</div>
			<div class="row-fluid">
				<div class="span3"><p>Sample Response</p></div>
			    <div class="span6"><p><code>=> ["classical", "rap", "gospel"]</code></p></div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<p><h2>Offers</h2></p>
			<h3>Klickpush supports getting an offer by genre. Offers are either for an album, or an individual track.(OAuth required)</h3>
			<div class="row-fluid">
				<div class="span3"><br /><p>GET /{genre}/single</p></div>
			    <div class="span6"><br /><p>Returns random song in a particular genre</p></div>
			</div>
			<div class="row-fluid">
				<div class="span3"><p>Example Request</p></div>
			    <div class="span6"><p>URL: http://api.klickpush.com/offers/rock/single</p></div>
			</div>
			<div class="row-fluid">
				<div class="span3"><p>Sample Response</p></div>
			    <div class="span6"><p><code>=> [{"artist_name"=>"Last 2 Weeks",
				     "artwork"=>"http://klickpushmedia.s3.amazonaws.com/c/0/c0ddf69668be_cropped.jpg",
				     "track"=>{
				       "track_name"=>"All My Friends", 
				       "urls"=>{
				         "original"=>"http://klickpushmedia.s3.amazonaws.com/8/3/83db8a0c99e5.mp3",
				         "preview"=>"http://klickpushmedia.s3.amazonaws.com/8/3/83db8a0c99e5_sample.mp3"},
				       "is_explicit"=>false
				     }
				  }]</code></p></div>
			</div>
		</div>	
	</div>
	<div class="row">
		<div class="span12">
				<div class="row-fluid">
					<div class="span3"><br /><p>GET /{genre}/album</p></div>
			    	<div class="span6"><br /><p>Returns random album in a particular genre</p></div>
				</div>
				<div class="row-fluid">
					<div class="span3"><p>Example Request</p></div>
				    <div class="span6"><p>URL: http://api.klickpush.com/offers/rock/album</p></div>
				</div>
				<div class="row-fluid">
					<div class="span3"><p>Sample Response</p></div>
				    <div class="span6"><p><code>=> [{"artist_name"=>"sounddrug",
					     "artwork"=>"http://klickpushmedia.s3.amazonaws.com/0/a/0a5f49a3997f_cropped.jpg",
					     "tracks"=>[
					       {"track_name"=>"Useless",
					        "urls"=>{
					          "original"=>"http://klickpushmedia.s3.amazonaws.com/a/4/a41d6f910c39.mp3",
					          "preview"=>"http://klickpushmedia.s3.amazonaws.com/a/4/a41d6f910c39_sample.mp3"},
					        "is_explicit"=>false, "is_featured"=>false
					       }
					     ]
					  }]</code></p></div>
				</div>
		</div>
	</div>
</div>

app/views/pages/forum.html.erb
<% provide(:title, 'Developer Forum') %>
<h1>Klick Push Developer Forum</h1>
<p>Forum will go here</p>

app/views/pages/getstarted.html.erb
<% provide(:title, 'Get Started') %>
<div class="container">
  <div class="row-fluid">
    <div class="span3">
    	<%= render 'layouts/platforms'%>
    </div>
	<div class="span9">
    	<h1>Get started with Klick Push</h1>
		<p>We want to make the integration process as easy as possible for you. Click on a platform to see how you can start earning more money with Klick Push in as little as 15 minutes. If there is a platform you'd like to see us integrate with, drop us a line at support@klickpush.com.
		</p>
	</div>
</div>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="left hero-unit">
	<h1>Increase Monetization Using Targeted Music</h1>
	<p>
		<h2>Klick Push provides developers with a music library to help incentivize users to purchase virtual goods inside of your games.</h2>
	</p>
	<%= link_to "Get Started", getstarted_path, class: "btn btn-large btn-primary" %>
</div>
<div class="row">
	<div class="container">
		<%= render 'layouts/usps'%>
	</div>
</div>

app/views/pages/html5.html.erb
<% provide(:title, 'Get Started | HTML5') %>
<div class="container">
  <div class="row-fluid">
    <div class="span3">
    	<%= render 'layouts/platforms'%>
    </div>
	<div class="span9">
    	<h1>Get started with HTML5</h1>
		<p>Coming soon.</p>
	</div>
</div>

app/views/pages/ios.html.erb
<% provide(:title, 'Get Started | iOS') %>
<div class="container">
  <div class="row-fluid">
    <div class="span3">
    	<%= render 'layouts/platforms'%>
    </div>
	<div class="span9">
    	<h1>Get started with iOS</h1>
		<p>Coming soon.</p>
	</div>
</div>

app/views/pages/pg.html.erb
<% provide(:title, 'Get Started | PhoneGap') %>
<div class="container">
  <div class="row-fluid">
    <div class="span3">
    	<%= render 'layouts/platforms'%>
    </div>
	<div class="span9">
    	<h1>Get started with PhoneGap</h1>
		<p>Coming soon.</p>
	</div>
</div>

app/views/pages/pricing.html.erb
<% provide(:title, 'Pricing') %>
<h1>Pricing Guide</h1>
<p>Price info will go here</p>

app/views/pages/support.html.erb
<h1>Pages#support</h1>
<p>Find me in app/views/pages/support.html.erb</p>

app/views/pages/unity.html.erb
<% provide(:title, 'Get Started | Unity') %>
<div class="container">
  <div class="row-fluid">
    <div class="span3">
    	<%= render 'layouts/platforms'%>
    </div>
	<div class="span9">
    	<h1>Get started with Unity</h1>
		<p>Coming soon.</p>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>